version: "3"
services:
  interfaces:
    # image: patrickkwang/robokop-interfaces
    build:
      context: ./docker
    env_file:
      - ../robokop/shared/robokop.env
    environment:
      - ROBOKOP_HOME=/home/murphy
      - NEO4J_HOST=neo4j
      - REDIS_HOST=redis
      - ROBOKOP_HOST=0.0.0.0
      - FLOWER_ADDRESS=0.0.0.0
      - SUPERVISOR_HOST=0.0.0.0
      # - TRANSLATOR_SERVICES_ROSETTAGRAPH_URL="bolt://${NEO4J_HOST}:${NEO4J_BOLT_PORT}"
      # - CELERY_BROKER_URL="redis://${REDIS_HOST}:${REDIS_PORT}/${BUILDER_REDIS_DB}"
      # - CELERY_RESULT_BACKEND="redis://${REDIS_HOST}:${REDIS_PORT}/${BUILDER_REDIS_DB}"
      # - FLOWER_BROKER_API="redis://${REDIS_HOST}:${REDIS_PORT}/${BUILDER_REDIS_DB}"
      # - FLOWER_PORT="${BUILDER_FLOWER_PORT}"
    ports:
      - "${ROBOKOP_BUILDER_PORT}:${ROBOKOP_BUILDER_PORT}"
      - "${BUILDER_FLOWER_PORT}:${BUILDER_FLOWER_PORT}"
      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    volumes:
      - ./neo4j/logs:/logs
      - .:/home/murphy/robokop-interfaces
    # stdin_open: true
    # tty: true
    # command: bash
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default