pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'deploy'
            additionalBuildArgs '--network=host'
            args "-v ${env.WORKSPACE}:/home/murphy/robokop-interfaces --entrypoint='' --network=host"
        }
    }
    triggers{
        cron ('* * * * */7')
    }
    environment {
        ROBOKOP_HOME="${env.WORKSPACE}"
        PYTHONPATH="${env.WORKSPACE}"
        OMNICORP_HOST="${params.OMNICORP_HOST}"
        OMNICORP_PORT="${params.OMNICORP_PORT}"
        OMNICORP_DB="${params.OMNICORP_DB}"
        OMNICORP_USER="${params.OMNICORP_USER}"
        OMNICORP_PASSWORD="${params.OMNICORP_PASSWORD}"

        NEO4J_HOST="${params.NEO4J_HOST}"
        NEO4J_USER="${params.NEO4J_USER}"
        NEO4J_HTTP_PORT="${params.NEO4J_HTTP_PORT}"
        NEO4J_BOLT_PORT="${params.NEO4J_BOLT_PORT}"
        NEO4J_HTTPS_PORT="${params.NEO4J_HTTPS_PORT}"
        NEO4J_PASSWORD="${params.NEO4J_PASSWORD}"

        PUBMED_CACHE_HOST="${params.PUBMED_CACHE_HOST}"
        PUBMED_CACHE_PORT="${params.PUBMED_CACHE_PORT}"
        PUBMED_CACHE_PASSWORD="${params.PUBMED_CACHE_PASSWORD}"

        CACHE_HOST="${params.CACHE_HOST}"
        CACHE_PORT="${params.CACHE_PORT}"
        CACHE_PASSWORD="${params.CACHE_PASSWORD}"

        TRANSLATOR_SERVICES_ROSETTAGRAPH_URL="bolt://${NEO4J_HOST}:${NEO4J_BOLT_PORT}"
        TRANSLATOR_SERVICES_ROSETTAGRAPH_NEO4J_PASSWORD="${NEO4J_PASSWORD}"
    }
    stages {
        stage ('setup logs dir') {
            steps {
                sh "mkdir -p ${ROBOKOP_HOME}/logs"
            }
        } 
        stage ('run tests') {
            steps {
                sh 'pytest greent/test'
            }
            post {
                failure {
                    sh "python monitoring/notify.py -e ${NOTIFICATION_RECIPIENTS} -m 'Client tests are failing.' -s ${BUILD_TAG}"                }
            }
        }
    }
}