pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'deploy'
            additionalBuildArgs '--network=host'
            args "-v ${env.WORKSPACE}:${ROBOKOP_HOME}/robokop-interfaces --entrypoint='' --network=host"
        }
    }
    environment {
        ROBOKOP_HOME=${params.ROBOKOP_HOME}
        OMNICORP_HOST=${params.OMNICORP_HOST}
        OMNICORP_PORT=${params.OMNICOPR_PORT}
        OMNICORP_DB=${params.OMNICORP_DB}
        OMNICORP_USER=${params.OMNICORP_USER}

        NEO4J_HOST=${params.NEO4J_HOST}
        NEO4J_USER=${params.NEO4J_USER}
        NEO4J_HTTP_PORT=${params.NEO4J_HTTP_PORT}
        NEO4J_BOLT_PORT=${params.NEO4J_BOLT_PORT}
        NEO4J_HTTPS_PORT=${params.NEO4J_HTTPS_PORT}

        PUBMED_CACHE_HOST=${params.PUBMED_CACHE_HOST}
        PUBMED_CACHE_PORT=${params.PUBMED_CACHE_PORT}

        CACHE_HOST=${params.CACHE_HOST}
        CACHE_PORT=${params.CACHE_PORT}
    }
    stages {
        stage ('setup env') {
            steps {
                sh '. deploy/setenv.sh'
            }
        } 
        stage ('run tests') {
            steps {
                sh 'pytest greent/test'
            }
        }
    }
}