pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'monitoring'
        }
    }
    triggers {
        cron ('*/5 * * * *')
    }
    parameters {
        string(name: 'TEST_MONITOR_FILE', defaultValue: '', description: 'The monitoring test file to run')
    }
    stages {
        stage ('Run Tests') {
            parallel {
                stage ('Monitoring Neo4j') {
                    steps {
                        sh "pytest monitoring/${params.TEST_NEO4J}"
                    }
                    post {
                        failure {
                            echo "failed on neo4j."
                        }
                    }
                }
                stage ('Monitoring main Redis') {
                    steps {
                        sh "pytest monitoring/${params.TEST_REDIS}"
                    } 
                    post {
                        fail {
                            echo "Failed on redis."
                        }
                    }
                }
                stage ('Monitoring Omnicorp') {
                    steps {
                        sh "pytest monitoring/${params.TEST_OMNICORP}"
                    }
                    post {
                        fail {
                            echo "Failed on omnicorp."
                        }
                    }
                }
                stage ('Monitoring Pubmed Cache') {
                    steps {
                        sh "pytest monitoring/${params.PUBMED_CACHE}"
                    }
                    post {
                        fail {
                            echo "Failed on Pubmed Cache."
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo "Everything seems good."
        }
        failure {
            echo "Something was wrong!!"
        }
    }
}