pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'monitoring'
        }
    }
    triggers {
        cron ('*/5 * * * *')
    }
    environment {
        TEST_NEO4J = 'test_neo4j_monitor.py'
        TEST_OMNICORP = 'test_omnicorp_monitoring.py'
        TEST_REDIS = 'test_redis_monitor.py'
        TEST_PUBMED_CACHE = 'test_pubmed_cache.py'
        TEST_MESSENGER = 'test_messenger.py'
        TEST_BUILDER = 'test_builder_api.py'
        TEST_RANKER = 'test_ranker_api.py'
        TEST_MANAGER = 'test_manager.py'
    }
    stages {
        stage ('Run Tests') {
            parallel {
                stage ('Monitoring Neo4j') {
                    steps {
                        sh "pytest monitoring/${TEST_NEO4J}"
                    }
                    post {
                        failure {
                            echo "failed on neo4j."
                        }
                    }
                }
                stage ('Monitoring main Redis') {
                    steps {
                        sh "pytest monitoring/${TEST_REDIS}"
                    } 
                    post {
                        failure {
                            echo "Failed on redis."
                        }
                    }
                }
                stage ('Monitoring Omnicorp') {
                    steps {
                        sh "pytest monitoring/${TEST_OMNICORP}"
                    }
                    post {
                        failure {
                            echo "Failed on omnicorp."
                        }
                    }
                }
                stage ('Monitoring Pubmed Cache') {
                    steps {
                        sh "pytest monitoring/${PUBMED_CACHE}"
                    }
                    post {
                        failure {
                            echo "Failed on Pubmed Cache."
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo "Everything seems good."
        }
        failure {
            echo "Something was wrong!!"
        }
    }
}