version: "3"
services:
  interfaces:
    # image: patrickkwang/robokop-interfaces
    build:
      context: .
    env_file:
      - ../../shared/robokop.env
    environment:
      - DEPLOY=docker
      - ROBOKOP_HOME=/home/murphy
      - NEO4J_HOST=neo4j
      - BROKER_HOST=broker
      - CACHE_HOST=cache
    ports:
      - "${BUILDER_PORT}:${BUILDER_PORT}"
      - "${FLOWER_PORT}:${FLOWER_PORT}"
      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    volumes:
      - ../../logs:/home/murphy/logs
      - ../../shared:/home/murphy/shared
      - ..:/home/murphy/robokop-interfaces
    # stdin_open: true
    # tty: true
    # command: bash
networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}_default