version: "3"
services:
  neo4j:
    build:
      context: ../neo4j/
    container_name: neo4j
    entrypoint:
      - /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ../../../../neo4j_data:/data
      - ../../../../neo4j_logs:/logs
      - ../../../../neo4j_ssl:/ssl
