apiVersion: v1
kind: Service
metadata:
  name: interfaces
spec:
  selector:
    app: robokop-interfaces
  ports:
    # interfaces web port
    - name: interfaces-web-port
      protocol: TCP
      port: 6010
      targetPort: 6010
    # intefaces supervisor port
    - name: intefaces-supervisor-port
      protocol: TCP
      port: 9002
      targetPort: 9002
    - name: build-cache-port
      protocol: TCP
      port: 6379
      targetPort: 6379
