apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-neo4j-data-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 300Gi
    hostPath:
      path: "/mnt/data/neo4j_data"
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-neo4j-data-pv
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-neo4j-data-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 300Gi
    storageClassName: robokop-neo4j-data-pv
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-neo4j-logs-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-neo4j-logs-pv
    hostPath:
      path: "/mnt/data/neo4j_logs"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-neo4j-logs-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: robokop-neo4j-logs-pv
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: robokop-neo4j-ssl-pv
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Ki
    persistentVolumeReclaimPolicy: Retain
    storageClassName: robokop-neo4j-ssl-pv
    hostPath:
      path: "/mnt/data/ssl"
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: robokop-neo4j-ssl-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Ki
    storageClassName: robokop-neo4j-ssl-pv

kind: List