apiVersion: v1
kind: Service
metadata:
  name: robokop-kg
spec:
  selector:
    app: robokop-kg
  type: NodePort
  ports:
    - name: neo4j-bolt-port
      protocol: TCP
      port: 7687
      targetPort: 7687
    - name: neo4j-http-port
      protocol: TCP
      port: 7474
      targetPort: 7474
