apiVersion: v1
kind: Service
metadata:
  name: robokop-cache
spec:
  selector:
    app: robokop-cache
  ports:
    # request cache redis port
    - name: robokop-cache-port
      protocol: TCP
      port: 6380
      targetPort: 6380